import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";
import NavBar from "@/app/_components/NavBar";
import DarkMode from "@/app/_components/DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`flex flex-col h-screen 
                bg-white dark:bg-[#161616] ${inter.className} dark:text-white`}>
                <div className="h-full overflow-y-auto">{children}</div>
                <NavBar />
                <DarkMode />
            </body>
        </html>
    );
}
