name: frontend-test

on:
  pull_request:
    branches:
      - develop-fe
    paths:
      - 'projects/fe/**'
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  test-when-pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projects/fe/

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: projects/fe/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
